### PR TITLE
Remove duplicated FakeTaskManager

### PR DESCRIPTION
**Pull request by pbortlov**
* remove fake_task_manager.py because it is a duplicate of utils.py

### CODE REVIEW

**Review by lipoja — APPROVED** [review]

**Comment by lipoja** [comment]
I thought that we can merge it safely before the https://github.com/release-engineering/pubtools-iib/pull/22
But now it looks like we should wait once https://github.com/release-engineering/pubtools-iib/pull/22 is merged and then rebase it on top of it. Then we can check our tests and if it passes we can be sure that it can be removed.

**Review by yashvardhannanavati — APPROVED** [review]

**Review by querti — CHANGES_REQUESTED** [review]
Could you fix the CI?

**Comment by pbortlov** [comment]
> Could you fix the CI?

@querti It will be fixed in previous PR

**Comment by pbortlov** [comment]
@midnightercz PTAL just quick one review

**Review by querti — APPROVED** [review]

**Pull request merged**
