### PR TITLE
Remove ability to push to quay

### PR DESCRIPTION
**Pull request by querti**
Since pub is not yet ready to support this functionality, the commit that adds this functionality will be added at a later date.

### CODE REVIEW

**Comment by lipoja** [comment]
I guess when we merge this we will introduce (revert) some issues that we should fix before release.
For example changes in DEPENDENCY_LINKS in setup.py, MANIFEST.in and some more.

**Comment by querti** [comment]
@lipoja This is not an automatic revert, I purposely included these changes so that the release would be possible. Some of the settings are strange (like in setup.py) but they worked in the past, so let's revert to them

**Review by midnightercz — APPROVED** [review]

**Comment by lipoja** [comment]
@querti OK, I thought that just revert of your previous commit.
However I think at least dependency_links should point to correct repo.

**Comment by querti** [comment]
> @querti OK, I thought that just revert of your previous commit.
> However I think at least dependency_links should point to correct repo.

Already fixed

**Comment by lipoja** [comment]
> > @querti OK, I thought that just revert of your previous commit.
> > However I think at least dependency_links should point to correct repo.
> 
> Already fixed

wow, you are faster then light. :zap:

**Review by lipoja — APPROVED** [review]

**Pull request merged**
